[build]
  functions = "api"
  command = "npm run build" # Adjust this if you have a specific build command

[build.environment]
  MONGODB_CONNECT_URI = "mongodb+srv://shashikiran:WDLPTIO0YSyYgk0x@cluster0.oypoubv.mongodb.net/mymongodb?retryWrites=true&w=majority&appName=Cluster0"
